"""RTAI model — a small transformer-like language model where attention is
replaced by an SRWM layer (self-referential weight matrix). Built in the spirit
of nanoGPT (KISS).

The SRWM layer holds, for each head, a weight matrix W that the model updates
with a delta rule:

    v̂ = W k            (retrieve)
    W ← W + β (v − v̂) kᵀ   (delta rule — self-correcting)
    o = W q            (read)

k, v, β, q are generated by the model from the current input (fixed "slow"
projections). The W matrices are the "fast" weights that change DURING the forward
pass → that is the self-modification.

Persistence: W can be passed in (state from before) and returned out. During
training we start from a learned W0 (the gradient flows through the recurrence →
we learn the ABILITY to self-modify). At deploy time we start from the saved state
and save it after every step → W accumulates across sessions and is NOT reset.
"""

from __future__ import annotations

from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F


@dataclass
class GPTConfig:
    vocab_size: int = 256          # default: byte-level
    block_size: int = 128
    n_layer: int = 4
    n_head: int = 4
    n_embd: int = 128              # head_dim = n_embd // n_head
    dropout: float = 0.0
    bias: bool = False
    w_decay: float = 1.0           # optional decay of fast weights (1.0 = none)
    srwm_mode: str = "recurrent"   # "recurrent" (readable, for visualization) | "chunk" (fast)
    chunk_size: int = 64           # block size for chunk-parallel mode

    @property
    def head_dim(self) -> int:
        assert self.n_embd % self.n_head == 0
        return self.n_embd // self.n_head


class SRWMLayer(nn.Module):
    """Self-referential / fast-weight layer with a delta rule.

    The fast weight W has shape (n_head, head_dim, head_dim) per sample in the batch.
    Processing is recurrent over time (KISS + lets us log ‖ΔW‖ per step).
    """

    def __init__(self, cfg: GPTConfig):
        super().__init__()
        self.n_head = cfg.n_head
        self.hd = cfg.head_dim
        self.w_decay = cfg.w_decay
        self.mode = cfg.srwm_mode
        self.chunk_size = cfg.chunk_size

        # Short causal (depthwise) convolution — each position sees a few preceding
        # tokens. Needed for the key→value binding in fast-weight recall (as in
        # DeltaNet / Mamba / GLA). Without it, associations only form indirectly via residuals.
        self.conv_k = 4
        self.conv = nn.Conv1d(cfg.n_embd, cfg.n_embd, kernel_size=self.conv_k,
                              groups=cfg.n_embd, bias=True)

        # Slow projections: from x_t produce q, k, v (each n_embd) and β (n_head).
        self.to_qkv = nn.Linear(cfg.n_embd, 3 * cfg.n_embd, bias=cfg.bias)
        self.to_beta = nn.Linear(cfg.n_embd, cfg.n_head, bias=True)
        self.proj = nn.Linear(cfg.n_embd, cfg.n_embd, bias=cfg.bias)
        self.drop = nn.Dropout(cfg.dropout)

        # Learned initial ("native") fast weight W0 — the starting point during training.
        self.W0 = nn.Parameter(torch.zeros(cfg.n_head, self.hd, self.hd))

    def init_state(self, batch_size: int, device, dtype=torch.float32) -> torch.Tensor:
        """Initial W for deploy/persistence (a copy of the learned W0 for each sample)."""
        return self.W0.detach().to(device=device, dtype=dtype).unsqueeze(0).repeat(
            batch_size, 1, 1, 1
        )

    def forward(self, x: torch.Tensor, W: torch.Tensor | None = None,
                return_delta: bool = False):
        """
        x: (B,T,n_embd);  W: (B,n_head,hd,hd) persistent state, or None (→ start from W0).
        Returns (out, W_final, delta_norms|None).

        Two numerically EQUIVALENT paths (see test_equiv.py):
          - 'recurrent' — readable step-by-step loop; can return ‖ΔW‖ (for visualization),
          - 'chunk'     — parallel delta rule over blocks, 10–50× faster to train.
        """
        B, T, _ = x.shape
        H, hd = self.n_head, self.hd

        # causal (depthwise) convolution — a position also sees a few preceding tokens
        xc = x.transpose(1, 2)
        xc = F.pad(xc, (self.conv_k - 1, 0))
        xc = self.conv(xc).transpose(1, 2)

        q, k, v = self.to_qkv(xc).split(H * hd, dim=2)
        q = F.normalize(q.view(B, T, H, hd), dim=-1).transpose(1, 2)  # (B,H,T,hd)
        k = F.normalize(k.view(B, T, H, hd), dim=-1).transpose(1, 2)
        v = v.view(B, T, H, hd).transpose(1, 2)
        beta = torch.sigmoid(self.to_beta(xc)).transpose(1, 2)        # (B,H,T)

        if W is None:
            W = self.W0[None].expand(B, H, hd, hd).contiguous()       # gradient flows into W0
        else:
            W = W.to(dtype=x.dtype)

        if self.mode == "chunk" and not return_delta:
            out, W, dn = *self._scan_chunk(q, k, v, beta, W), None
        else:
            out, W, dn = self._scan_recurrent(q, k, v, beta, W, return_delta)

        out = out.transpose(1, 2).reshape(B, T, H * hd)               # (B,H,T,hd)→(B,T,E)
        return self.drop(self.proj(out)), W, dn

    def _scan_recurrent(self, q, k, v, beta, W, return_delta):
        """Readable version: step by step, W = W + β(v − Wk)kᵀ, read after write."""
        T = q.shape[2]
        outs, dnorms = [], ([] if return_delta else None)
        for t in range(T):
            k_t, v_t, q_t = k[:, :, t], v[:, :, t], q[:, :, t]        # (B,H,hd)
            b_t = beta[:, :, t].unsqueeze(-1)
            v_hat = torch.einsum("bhij,bhj->bhi", W, k_t)
            dW = torch.einsum("bhi,bhj->bhij", b_t * (v_t - v_hat), k_t)
            W = self.w_decay * W + dW                                 # SELF-MODIFICATION OF WEIGHTS
            outs.append(torch.einsum("bhij,bhj->bhi", W, q_t))        # read after write
            if return_delta:
                dnorms.append(dW.flatten(1).norm(dim=1))              # (B,)
        dn = torch.stack(dnorms, dim=1) if return_delta else None     # (B,T)
        return torch.stack(outs, dim=2), W, dn                        # (B,H,T,hd)

    def _scan_chunk(self, q, k, v, beta, W):
        """Parallel delta rule over blocks (DeltaNet). Assumes w_decay=1."""
        assert self.w_decay == 1.0, "chunk mode assumes w_decay=1"
        B, H, T, hd = q.shape
        C = self.chunk_size
        S = W                                                         # (B,H,hd,hd): v = S·k
        eye = torch.eye(C, device=q.device, dtype=q.dtype)
        outs = []
        for s in range(0, T, C):
            e = min(s + C, T)
            c = e - s
            Kc, Vc, Qc = k[:, :, s:e], v[:, :, s:e], q[:, :, s:e]     # (B,H,c,hd)
            Bc = beta[:, :, s:e]                                      # (B,H,c)
            # solve the intra-block dependencies of the delta rule: (I+A)U = β(V − S·K)
            A = torch.tril(Bc.unsqueeze(-1) * (Kc @ Kc.transpose(-1, -2)), diagonal=-1)
            M = A + eye[:c, :c]                                       # unit-lower-triangular
            rhs = Bc.unsqueeze(-1) * (Vc - Kc @ S.transpose(-1, -2))  # (B,H,c,hd)
            U = torch.linalg.solve_triangular(M, rhs, upper=False, unitriangular=True)
            QKt = torch.tril(Qc @ Kc.transpose(-1, -2), diagonal=0)   # j ≤ t (read after write)
            outs.append(Qc @ S.transpose(-1, -2) + QKt @ U)          # (B,H,c,hd)
            S = S + U.transpose(-1, -2) @ Kc                          # advance the state to the end of the block
        return torch.cat(outs, dim=2), S                              # (B,H,T,hd), (B,H,hd,hd)

    def step(self, x, W, conv_state):
        """Streaming step for a PERSISTENT run: processes x (B,T,E) tied to the
        previous context via conv_state (the last conv_k-1 inputs), so the causal
        convolution has the right context even when fed one token at a time. Carries and
        returns both W and conv_state → W accumulates across turns/sessions (is not reset)."""
        B, T, E = x.shape
        H, hd = self.n_head, self.hd
        if conv_state is None:
            conv_state = x.new_zeros(B, self.conv_k - 1, E)
        x_full = torch.cat([conv_state, x], dim=1)                     # (B, k-1+T, E)
        xc = self.conv(x_full.transpose(1, 2)).transpose(1, 2)         # (B, T, E)
        new_conv_state = x_full[:, -(self.conv_k - 1):]                # (B, k-1, E)
        q, k, v = self.to_qkv(xc).split(H * hd, dim=2)
        q = F.normalize(q.view(B, T, H, hd), dim=-1).transpose(1, 2)
        k = F.normalize(k.view(B, T, H, hd), dim=-1).transpose(1, 2)
        v = v.view(B, T, H, hd).transpose(1, 2)
        beta = torch.sigmoid(self.to_beta(xc)).transpose(1, 2)
        out, W, _ = self._scan_recurrent(q, k, v, beta, W, False)
        out = out.transpose(1, 2).reshape(B, T, H * hd)
        return self.drop(self.proj(out)), W, new_conv_state


class MLP(nn.Module):
    def __init__(self, cfg: GPTConfig):
        super().__init__()
        self.fc = nn.Linear(cfg.n_embd, 4 * cfg.n_embd, bias=cfg.bias)
        self.proj = nn.Linear(4 * cfg.n_embd, cfg.n_embd, bias=cfg.bias)
        self.drop = nn.Dropout(cfg.dropout)

    def forward(self, x):
        return self.drop(self.proj(F.gelu(self.fc(x))))


class Block(nn.Module):
    def __init__(self, cfg: GPTConfig):
        super().__init__()
        self.ln1 = nn.LayerNorm(cfg.n_embd, bias=cfg.bias)
        self.srwm = SRWMLayer(cfg)
        self.ln2 = nn.LayerNorm(cfg.n_embd, bias=cfg.bias)
        self.mlp = MLP(cfg)

    def forward(self, x, W=None, return_delta=False):
        y, W_new, dn = self.srwm(self.ln1(x), W, return_delta)
        x = x + y
        x = x + self.mlp(self.ln2(x))
        return x, W_new, dn

    def step(self, x, W, conv_state):
        y, W, cs = self.srwm.step(self.ln1(x), W, conv_state)
        x = x + y
        x = x + self.mlp(self.ln2(x))
        return x, W, cs


class RTAIModel(nn.Module):
    """A small language model with persistent SRWM layers."""

    def __init__(self, cfg: GPTConfig):
        super().__init__()
        self.cfg = cfg
        self.tok_emb = nn.Embedding(cfg.vocab_size, cfg.n_embd)
        self.drop = nn.Dropout(cfg.dropout)
        self.blocks = nn.ModuleList([Block(cfg) for _ in range(cfg.n_layer)])
        self.ln_f = nn.LayerNorm(cfg.n_embd, bias=cfg.bias)
        self.head = nn.Linear(cfg.n_embd, cfg.vocab_size, bias=False)
        # weight tying
        self.head.weight = self.tok_emb.weight
        self.apply(self._init_weights)
        n = sum(p.numel() for p in self.parameters())
        print(f"[RTAIModel] parameters: {n/1e6:.2f}M")

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)
            if m.bias is not None:
                nn.init.zeros_(m.bias)
        elif isinstance(m, nn.Embedding):
            nn.init.normal_(m.weight, mean=0.0, std=0.02)

    def init_states(self, batch_size: int, device, dtype=torch.float32):
        """Persistent states (one W matrix per layer) for deploy."""
        return [blk.srwm.init_state(batch_size, device, dtype) for blk in self.blocks]

    def forward(self, idx, targets=None, states=None, return_delta=False):
        """
        idx: (B, T) tokens.
        states: list of W per layer (persistence) or None (start from W0).
        Returns: logits, loss|None, new_states, delta_norms|None
        """
        B, T = idx.shape
        x = self.drop(self.tok_emb(idx))
        new_states = []
        all_dn = [] if return_delta else None
        for i, blk in enumerate(self.blocks):
            W_in = states[i] if states is not None else None
            x, W_out, dn = blk(x, W_in, return_delta)
            new_states.append(W_out)
            if return_delta:
                all_dn.append(dn)
        x = self.ln_f(x)
        logits = self.head(x)
        loss = None
        if targets is not None:
            loss = F.cross_entropy(
                logits.view(-1, logits.size(-1)), targets.view(-1), ignore_index=-1
            )
        return logits, loss, new_states, all_dn

    @torch.no_grad()
    def generate(self, idx, max_new_tokens, states=None, temperature=1.0, top_k=None):
        """Autoregressive generation (recurrently correct).

        The prompt is processed once, then tokens are fed one at a time with the carried
        state W (no block_size window — the recurrent state uses constant memory). The state
        W self-modifies along the way and is returned out → save it for persistence.
        """
        self.eval()

        def sample(logits_last):
            logits_last = logits_last / max(temperature, 1e-6)
            if top_k is not None:
                v, _ = torch.topk(logits_last, min(top_k, logits_last.size(-1)))
                logits_last[logits_last < v[:, [-1]]] = -float("inf")
            probs = F.softmax(logits_last, dim=-1)
            return torch.multinomial(probs, num_samples=1)

        logits, _, states, _ = self(idx, states=states)   # process the prompt once
        for _ in range(max_new_tokens):
            nxt = sample(logits[:, -1, :])
            idx = torch.cat([idx, nxt], dim=1)
            logits, _, states, _ = self(nxt, states=states)  # feed only the new token
        return idx, states

    @torch.no_grad()
    def generate_lm(self, idx, max_new_tokens, temperature=1.0, top_k=None):
        """Generation for the language model (with causal convolution): each step recomputes
        a sliding window of the last block_size tokens, so the convolution sees the right context.
        (This is NOT the persistent mode — W is computed from the window; persistence across
        sessions is the next step for the language model, see README.)"""
        self.eval()
        for _ in range(max_new_tokens):
            idx_cond = idx[:, -self.cfg.block_size:]
            logits, _, _, _ = self(idx_cond, states=None)
            logits = logits[:, -1, :] / max(temperature, 1e-6)
            if top_k is not None:
                v, _ = torch.topk(logits, min(top_k, logits.size(-1)))
                logits[logits < v[:, [-1]]] = -float("inf")
            probs = F.softmax(logits, dim=-1)
            nxt = torch.multinomial(probs, num_samples=1)
            idx = torch.cat([idx, nxt], dim=1)
        return idx

    def init_conv_states(self, n_layer=None):
        """Empty conv-context for streaming (per layer None → the first step zeroes it)."""
        return [None for _ in self.blocks]

    def forward_stream(self, idx, states, conv_states):
        """Streaming pass: carries both W and the conv-context per layer (persistent run).
        states/conv_states must be provided (see init_states / init_conv_states)."""
        x = self.drop(self.tok_emb(idx))
        new_states, new_cs = [], []
        for i, blk in enumerate(self.blocks):
            x, W, cs = blk.step(x, states[i], conv_states[i])
            new_states.append(W)
            new_cs.append(cs)
        return self.head(self.ln_f(x)), new_states, new_cs

    @torch.no_grad()
    def generate_stream(self, idx, max_new_tokens, states, conv_states,
                        temperature=1.0, top_k=None):
        """PERSISTENT generation: processes the input, then generates token by token while
        both W and the conv-context are carried forward (not reset) → memory persists. Returns
        (generated_tokens, states, conv_states) — save the states for the next turn/session."""
        self.eval()
        logits, states, conv_states = self.forward_stream(idx, states, conv_states)
        gen = []
        for _ in range(max_new_tokens):
            lg = logits[:, -1, :] / max(temperature, 1e-6)
            if top_k is not None:
                v, _ = torch.topk(lg, min(top_k, lg.size(-1)))
                lg[lg < v[:, [-1]]] = -float("inf")
            nxt = torch.multinomial(F.softmax(lg, dim=-1), num_samples=1)
            gen.append(nxt)
            logits, states, conv_states = self.forward_stream(nxt, states, conv_states)
        gen = torch.cat(gen, dim=1) if gen else idx[:, :0]
        return gen, states, conv_states
